POST http://localhost:8080/api/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX2VtYWlsIjoiZXpoaWxAZ21haWwuY29tIiwiZXhwIjoxNzQwMjA0NjU4fQ.8klYb48r2BWhiGyc4yIoT9kFId3HPvdDYlHl_D-LuvE

{
  "title": "Create a new task",
  "assigned_to_id": 1,
  "due_date": "2024-02-21T14:30:00Z",
  "description": "Create a new task for the API test"
}